services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: trueblocks-api
    depends_on:
      - trueblocks
    expose:
      - "3000"
    restart: unless-stopped

  trueblocks:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UPSTREAM_VER: develop
    container_name: trueblocks-core
    volumes:
      - type: volume
        source: cache
        target: /cache
      - type: volume
        source: unchained
        target: /unchained
    restart: unless-stopped

volumes:
  cache:
  unchained:
